export default {
  icHome: require('../assets/icons/HomeIcon.png'),
  icServices: require('../assets/icons/ServicesIcon.png'),
  icAppointment: require('../assets/icons/AppointmentIcon.png'),
  icProfile: require('../assets/icons/ProfileIcon.png'),
  icClose: require('../assets/icons/close.png'),
  icDelete: require('../assets/icons/Delete.png'),
  icPending: require('../assets/icons/PendingIcon.png'),
  icRecord: require('../assets/icons/RecordIcon.png'),
  icOut: require('../assets/icons/LogoutIcon.png'),
  icCalendar: require('../assets/icons/CalendarIcon.png'),
  icClock: require('../assets/icons/ClockIcon.png'),
  icPhone: require('../assets/icons/telephone.png'),
  icFB: require('../assets/icons/facebook.png'),
  icEmail: require('../assets/icons/email.png'),
  icLocation: require('../assets/icons/location.png'),
  icDeveloper: require('../assets/icons/developer.png'),
  icAbout: require('../assets/icons/about.png'),

  //Services
  service1: require('../assets/SP/SP_diagnosis.jpg'),
  service2: require('../assets/SP/SP_surgical.jpg'),
  service3: require('../assets/SP/SP_vaccine.jpg'),
  service4: require('../assets/SP/SP_consult.jpg'),
  service5: require('../assets/SP/SP_laboratory.jpg'),
  service6: require('../assets/SP/SP_dentistry.jpg'),
  service7: require('../assets/SP/SP_radiology.jpg'),
  service8: require('../assets/SP/SP_pharmacy.jpg'),
  service9: require('../assets/SP/SP_grooming.jpg'),

  pets: require('../assets/SP/Pet.png'),
  daisy: require('../assets/icons/Daisy.png'),

  logo: require('../assets/icons/logo.png'),

  onboardingA: require('../assets/onboarding/onboarding1.png'),
  onboardingB: require('../assets/onboarding/onboarding2.png'),
  onboardingC: require('../assets/onboarding/onboarding3.png'),
  onboardingD: require('../assets/onboarding/onboarding4.png'),
  bulletsA: require('../assets/onboarding/bullets1.png'),
  bulletsB: require('../assets/onboarding/bullets2.png'),
  bulletsC: require('../assets/onboarding/bullets3.png'),
  bulletsD: require('../assets/onboarding/bullets4.png'),
};
